/*
 * Copyright 2014-2026 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package ktorbuild

import io.ktor.client.plugins.cookies.*
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.security.MessageDigest
import java.time.Duration

/** Downloads the Public Suffix List and generates the processed binary resource and its license notice. */
@DisableCachingByDefault(because = "The task explicitly fetches the latest upstream list")
abstract class UpdatePublicSuffixList : DefaultTask() {
    @get:Input
    abstract val sourceUrl: Property<String>

    @get:OutputFile
    abstract val binaryDestination: RegularFileProperty

    @get:OutputFile
    abstract val noticeDestination: RegularFileProperty

    @TaskAction
    fun update() {
        val source = sourceUrl.get()
        val request = HttpRequest.newBuilder(URI(source))
            .header("User-Agent", "Ktor Public Suffix List updater")
            .timeout(Duration.ofSeconds(60))
            .GET()
            .build()
        val client = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(30))
            .followRedirects(HttpClient.Redirect.NORMAL)
            .build()
        val response = client.send(request, HttpResponse.BodyHandlers.ofByteArray())

        check(response.statusCode() in 200..299) {
            "Failed to download the Public Suffix List from $source: HTTP ${response.statusCode()}"
        }

        val sourceBytes = response.body()
        val content = StandardCharsets.UTF_8.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT)
            .decode(ByteBuffer.wrap(sourceBytes))
            .toString()
        val rules = parsePublicSuffixList(content, source)
        val checksum = MessageDigest.getInstance("SHA-256").digest(sourceBytes).toHexString()
        val binary = renderPublicSuffixList(rules)
        val notice = renderNotice(source, checksum).toByteArray(StandardCharsets.UTF_8)

        writeAtomically(binaryDestination.get().asFile.toPath(), binary)
        writeAtomically(noticeDestination.get().asFile.toPath(), notice)
    }
}

private fun renderPublicSuffixList(rules: PublicSuffixListRules): ByteArray {
    val ruleBytes = rules.rules.sorted().toRuleBlock()
    val exceptionBytes = rules.exceptions.sorted().toRuleBlock()
    return ByteBuffer.allocate(8 + ruleBytes.size + exceptionBytes.size)
        .putInt(ruleBytes.size)
        .put(ruleBytes)
        .putInt(exceptionBytes.size)
        .put(exceptionBytes)
        .array()
}

private fun List<String>.toRuleBlock(): ByteArray {
    if (isEmpty()) return ByteArray(0)
    return joinToString(separator = "\n", postfix = "\n").toByteArray(StandardCharsets.UTF_8)
}

private fun renderNotice(sourceUrl: String, checksum: String): String = """
    |Mozilla Public Suffix List
    |
    |Source: $sourceUrl
    |SHA-256: $checksum
    |
    |This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
    |If a copy of the MPL was not distributed with this file, You can obtain one at
    |https://mozilla.org/MPL/2.0/.
    |
    |Generated by :ktor-client-cookies-public-suffix:updatePublicSuffixList.
""".trimMargin() + "\n"

private fun writeAtomically(destination: Path, content: ByteArray) {
    Files.createDirectories(destination.parent)
    if (Files.exists(destination) && Files.readAllBytes(destination).contentEquals(content)) return

    val temporary = Files.createTempFile(destination.parent, ".${destination.fileName}-", ".tmp")
    try {
        Files.write(temporary, content)
        try {
            Files.move(
                temporary,
                destination,
                StandardCopyOption.ATOMIC_MOVE,
                StandardCopyOption.REPLACE_EXISTING
            )
        } catch (_: AtomicMoveNotSupportedException) {
            Files.move(temporary, destination, StandardCopyOption.REPLACE_EXISTING)
        }
    } finally {
        Files.deleteIfExists(temporary)
    }
}

private fun ByteArray.toHexString(): String = joinToString(separator = "") { byte ->
    (byte.toInt() and 0xff).toString(16).padStart(2, '0')
}
