# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: true
reviews:
  high_level_summary: false
  collapse_walkthrough: true
  sequence_diagrams: false
  assess_linked_issues: false
  related_issues: false
  poem: false
  auto_review:
    base_branches:
      - main
      - release/*
chat:
  integrations:
    jira:
      usage: disabled
