/*
 * Copyright 2014-2023 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package io.ktor.network.quic.connections

import io.ktor.network.quic.bytes.*
import io.ktor.utils.io.core.*
import kotlin.jvm.*
import kotlin.random.*

@JvmInline
internal value class QUICConnectionID(val value: ByteArray) {
    val size get() = value.size

    companion object {
        val EMPTY = QUICConnectionID(byteArrayOf())

        fun new(): QUICConnectionID {
            // todo fix random
            return QUICConnectionID(Random.nextBytes(endpointSCIDLength))
        }

        /**
         * Length of the CIDs generated by this endpoint
         */
        const val endpointSCIDLength: Int = 16
    }
}

@Suppress("NOTHING_TO_INLINE")
internal inline fun ByteArray.asCID() = QUICConnectionID(this)

internal infix fun QUICConnectionID.neq(other: QUICConnectionID): Boolean {
    return !eq(other)
}

internal infix fun QUICConnectionID.eq(other: QUICConnectionID): Boolean {
    return value.contentEquals(other.value)
}

internal fun BytePacketBuilder.writeConnectionID(id: QUICConnectionID) {
    writeVarInt(id.size)
    writeFully(id.value)
}
