/*
 * Copyright 2014-2025 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

// Declarations generated by Dukat https://github.com/Kotlin/dukat and modified

package io.ktor.client.webrtc.browser

import org.w3c.dom.mediacapture.MediaDevices

public open external class DOMException {
    public var code: Number
    public var message: String
    public var name: String
}

public external interface ReadonlyMap<K> {
    public fun entries(): Iterator<dynamic>
    public fun keys(): Iterable<K>
    public fun values(): Iterator<dynamic>
    public fun forEach(
        callbackfn: (value: dynamic, key: K, map: ReadonlyMap<K>) -> Unit,
        thisArg: Any = definedExternally
    )

    public fun <V> get(key: K): V?
    public fun has(key: K): Boolean
    public val size: Number
}

public external interface Navigator {
    public val mediaDevices: MediaDevices
}

public external val navigator: Navigator
