/*
 * Copyright 2014-2025 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

// Declarations generated by Dukat https://github.com/Kotlin/dukat and modified

package io.ktor.client.webrtc.browser

import org.w3c.dom.mediacapture.MediaDevices

public open external class DOMException {
    public val code: Number
    public val message: String
    public val name: String

    public companion object {
        public val ABORT_ERR: Number
        public val DATA_CLONE_ERR: Number
        public val DOMSTRING_SIZE_ERR: Number
        public val HIERARCHY_REQUEST_ERR: Number
        public val INDEX_SIZE_ERR: Number
        public val INUSE_ATTRIBUTE_ERR: Number
        public val INVALID_ACCESS_ERR: Number
        public val INVALID_CHARACTER_ERR: Number
        public val INVALID_MODIFICATION_ERR: Number
        public val INVALID_NODE_TYPE_ERR: Number
        public val INVALID_STATE_ERR: Number
        public val NAMESPACE_ERR: Number
        public val NETWORK_ERR: Number
        public val NOT_FOUND_ERR: Number
        public val NOT_SUPPORTED_ERR: Number
        public val NO_DATA_ALLOWED_ERR: Number
        public val NO_MODIFICATION_ALLOWED_ERR: Number
        public val QUOTA_EXCEEDED_ERR: Number
        public val SECURITY_ERR: Number
        public val SYNTAX_ERR: Number
        public val TIMEOUT_ERR: Number
        public val TYPE_MISMATCH_ERR: Number
        public val URL_MISMATCH_ERR: Number
        public val VALIDATION_ERR: Number
        public val WRONG_DOCUMENT_ERR: Number
    }
}

public external interface ReadonlyMap<K> {
    public fun entries(): Iterator<dynamic>
    public fun keys(): Iterable<K>
    public fun values(): Iterator<dynamic>
    public fun forEach(
        callbackfn: (value: dynamic, key: K, map: ReadonlyMap<K>) -> Unit,
        thisArg: Any = definedExternally
    )

    public fun <V> get(key: K): V?
    public fun has(key: K): Boolean
    public val size: Number
}

public external interface Navigator {
    public val mediaDevices: MediaDevices
}

public external val navigator: Navigator
