/*
 * Copyright 2014-2025 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

// Declarations generated by Dukat https://github.com/Kotlin/dukat and modified

package io.ktor.client.webrtc.browser

import org.w3c.dom.mediacapture.MediaDevices

public typealias JsUndefined = JsAny?

public open external class DOMException {
    public val code: JsNumber
    public val message: JsString
    public val name: JsString

    public companion object {
        public val ABORT_ERR: JsNumber
        public val DATA_CLONE_ERR: JsNumber
        public val DOMSTRING_SIZE_ERR: JsNumber
        public val HIERARCHY_REQUEST_ERR: JsNumber
        public val INDEX_SIZE_ERR: JsNumber
        public val INUSE_ATTRIBUTE_ERR: JsNumber
        public val INVALID_ACCESS_ERR: JsNumber
        public val INVALID_CHARACTER_ERR: JsNumber
        public val INVALID_MODIFICATION_ERR: JsNumber
        public val INVALID_NODE_TYPE_ERR: JsNumber
        public val INVALID_STATE_ERR: JsNumber
        public val NAMESPACE_ERR: JsNumber
        public val NETWORK_ERR: JsNumber
        public val NOT_FOUND_ERR: JsNumber
        public val NOT_SUPPORTED_ERR: JsNumber
        public val NO_DATA_ALLOWED_ERR: JsNumber
        public val NO_MODIFICATION_ALLOWED_ERR: JsNumber
        public val QUOTA_EXCEEDED_ERR: JsNumber
        public val SECURITY_ERR: JsNumber
        public val SYNTAX_ERR: JsNumber
        public val TIMEOUT_ERR: JsNumber
        public val TYPE_MISMATCH_ERR: JsNumber
        public val URL_MISMATCH_ERR: JsNumber
        public val VALIDATION_ERR: JsNumber
        public val WRONG_DOCUMENT_ERR: JsNumber
    }
}

public external interface ReadonlyMap<K : JsAny> : JsAny {
    public fun entries(): JsAny
    public fun keys(): JsAny
    public fun values(): JsAny
    public fun forEach(
        callbackfn: (value: JsAny, key: K, map: ReadonlyMap<K>) -> Unit,
        thisArg: JsAny = definedExternally
    )

    public fun <V : JsAny> get(key: K): V?
    public fun has(key: K): JsBoolean
    public val size: JsNumber
}

public external interface Navigator {
    public val mediaDevices: MediaDevices
}

public external val navigator: Navigator
