

package io.ktor.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.ktor.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("ktor-compiler-plugin/testData/openapi")
@TestDataPath("$PROJECT_ROOT")
public class OpenapiTestGenerated extends AbstractOpenapiTest {
  @Test
  public void testAllFilesPresentInOpenapi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("ktor-compiler-plugin/testData/openapi"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("CallHandlerFunctions.kt")
  public void testCallHandlerFunctions() {
    runTest("ktor-compiler-plugin/testData/openapi/CallHandlerFunctions.kt");
  }

  @Test
  @TestMetadata("KDocOptions.kt")
  public void testKDocOptions() {
    runTest("ktor-compiler-plugin/testData/openapi/KDocOptions.kt");
  }

  @Test
  @TestMetadata("MarkdownOptions.kt")
  public void testMarkdownOptions() {
    runTest("ktor-compiler-plugin/testData/openapi/MarkdownOptions.kt");
  }

  @Test
  @TestMetadata("Nesting.kt")
  public void testNesting() {
    runTest("ktor-compiler-plugin/testData/openapi/Nesting.kt");
  }

  @Test
  @TestMetadata("OddReferences.kt")
  public void testOddReferences() {
    runTest("ktor-compiler-plugin/testData/openapi/OddReferences.kt");
  }

  @Test
  @TestMetadata("Parameters.kt")
  public void testParameters() {
    runTest("ktor-compiler-plugin/testData/openapi/Parameters.kt");
  }

  @Test
  @TestMetadata("RareCalls.kt")
  public void testRareCalls() {
    runTest("ktor-compiler-plugin/testData/openapi/RareCalls.kt");
  }

  @Test
  @TestMetadata("Recursion.kt")
  public void testRecursion() {
    runTest("ktor-compiler-plugin/testData/openapi/Recursion.kt");
  }

  @Test
  @TestMetadata("Resources.kt")
  public void testResources() {
    runTest("ktor-compiler-plugin/testData/openapi/Resources.kt");
  }

  @Test
  @TestMetadata("Responses.kt")
  public void testResponses() {
    runTest("ktor-compiler-plugin/testData/openapi/Responses.kt");
  }

  @Test
  @TestMetadata("RouteFunctions.kt")
  public void testRouteFunctions() {
    runTest("ktor-compiler-plugin/testData/openapi/RouteFunctions.kt");
  }

  @Test
  @TestMetadata("TypeParameters.kt")
  public void testTypeParameters() {
    runTest("ktor-compiler-plugin/testData/openapi/TypeParameters.kt");
  }
}
