

package io.ktor.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.ktor.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("ktor-compiler-plugin/testData/openapi")
@TestDataPath("$PROJECT_ROOT")
public class OpenapiTestGenerated extends AbstractOpenapiTest {
  private void run(String fileName) {
    runTest("ktor-compiler-plugin/testData/openapi/" + fileName);
  }

  @Test
  public void testAllFilesPresentInOpenapi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("ktor-compiler-plugin/testData/openapi"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("CallHandlerFunctions.kt")
  public void testCallHandlerFunctions() {
    run("CallHandlerFunctions.kt");
  }

  @Test
  @TestMetadata("KDocOptions.kt")
  public void testKDocOptions() {
    run("KDocOptions.kt");
  }

  @Test
  @TestMetadata("MarkdownOptions.kt")
  public void testMarkdownOptions() {
    run("MarkdownOptions.kt");
  }

  @Test
  @TestMetadata("Nesting.kt")
  public void testNesting() {
    run("Nesting.kt");
  }

  @Test
  @TestMetadata("NullableValueClasses.kt")
  public void testNullableValueClasses() {
    run("NullableValueClasses.kt");
  }

  @Test
  @TestMetadata("OddReferences.kt")
  public void testOddReferences() {
    run("OddReferences.kt");
  }

  @Test
  @TestMetadata("Parameters.kt")
  public void testParameters() {
    run("Parameters.kt");
  }

  @Test
  @TestMetadata("RareCalls.kt")
  public void testRareCalls() {
    run("RareCalls.kt");
  }

  @Test
  @TestMetadata("Recursion.kt")
  public void testRecursion() {
    run("Recursion.kt");
  }

  @Test
  @TestMetadata("Resources.kt")
  public void testResources() {
    run("Resources.kt");
  }

  @Test
  @TestMetadata("Responses.kt")
  public void testResponses() {
    run("Responses.kt");
  }

  @Test
  @TestMetadata("RouteFunctions.kt")
  public void testRouteFunctions() {
    run("RouteFunctions.kt");
  }

  @Test
  @TestMetadata("TypeParameters.kt")
  public void testTypeParameters() {
    run("TypeParameters.kt");
  }
}
